# Generated by Django 4.2.5 on 2023-09-25 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='игра')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0, message='Мы деньги за игры не даём!')], verbose_name='цена')),
                ('poster', models.ImageField(upload_to='posters', verbose_name='постер')),
                ('rate', models.FloatField(max_length=5, verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ('-id',),
            },
        ),
    ]
