# Generated by Django 4.2.5 on 2023-10-20 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='скрыта ли'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='datetime_finished',
            field=models.DateField(default=datetime.datetime(2023, 11, 19, 21, 7, 40, 856771), verbose_name='Дата завершения'),
        ),
    ]
