# Generated by Django 4.2.5 on 2023-10-23 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_is_hidden_alter_subscribe_datetime_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='datetime_finished',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 20, 59, 18, 26173), verbose_name='Дата завершения'),
        ),
    ]
